version: '3.8'

services:

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  rspamd:
    image: rspamd/rspamd
    ports:
      - "11334:11334"
    volumes:
      - ./rspamd-config/worker-controller.inc:/etc/rspamd/local.d/worker-controller.inc
      - ./rspamd-config/local.d/phishing_test.conf:/etc/rspamd/local.d/phishing_test.conf

  analyzer:
    build: .
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    depends_on:
      - mailpit
      - rspamd
    environment:
      - MAILPIT_HOST=mailpit
      - MAILPIT_PORT=1025
      - MAILPIT_API=http://mailpit:8025/api
    restart: unless-stopped